# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hiperlink_pb2 as hiperlink__pb2


class PluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnLoad = channel.unary_unary(
                '/proto.Plugin/OnLoad',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.OnUnload = channel.unary_unary(
                '/proto.Plugin/OnUnload',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.OnInstall = channel.unary_unary(
                '/proto.Plugin/OnInstall',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.OnUninstall = channel.unary_unary(
                '/proto.Plugin/OnUninstall',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.OnStart = channel.unary_unary(
                '/proto.Plugin/OnStart',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.OnStop = channel.unary_unary(
                '/proto.Plugin/OnStop',
                request_serializer=hiperlink__pb2.EventsRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.EventsResponse.FromString,
                )
        self.Interaction = channel.unary_unary(
                '/proto.Plugin/Interaction',
                request_serializer=hiperlink__pb2.InteractionRequest.SerializeToString,
                response_deserializer=hiperlink__pb2.InteractionResponse.FromString,
                )


class PluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnUnload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnInstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnUninstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.OnLoad,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'OnUnload': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUnload,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'OnInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.OnInstall,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'OnUninstall': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUninstall,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'OnStart': grpc.unary_unary_rpc_method_handler(
                    servicer.OnStart,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'OnStop': grpc.unary_unary_rpc_method_handler(
                    servicer.OnStop,
                    request_deserializer=hiperlink__pb2.EventsRequest.FromString,
                    response_serializer=hiperlink__pb2.EventsResponse.SerializeToString,
            ),
            'Interaction': grpc.unary_unary_rpc_method_handler(
                    servicer.Interaction,
                    request_deserializer=hiperlink__pb2.InteractionRequest.FromString,
                    response_serializer=hiperlink__pb2.InteractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Plugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnLoad',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnUnload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnUnload',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnInstall',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnUninstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnUninstall',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnStart',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/OnStop',
            hiperlink__pb2.EventsRequest.SerializeToString,
            hiperlink__pb2.EventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Interaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Plugin/Interaction',
            hiperlink__pb2.InteractionRequest.SerializeToString,
            hiperlink__pb2.InteractionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
