# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hiperlink.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhiperlink.proto\x12\x05proto\"(\n\rEventsRequest\x12\x17\n\x0fpluginInterface\x18\x01 \x01(\t\"\x1f\n\x0e\x45ventsResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\"?\n\x12InteractionRequest\x12\x17\n\x0fpluginInterface\x18\x01 \x01(\t\x12\x10\n\x08\x66unction\x18\x02 \x01(\t\"$\n\x13InteractionResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xa3\x03\n\x06Plugin\x12\x35\n\x06OnLoad\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12\x37\n\x08OnUnload\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12\x38\n\tOnInstall\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12:\n\x0bOnUninstall\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12\x36\n\x07OnStart\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12\x35\n\x06OnStop\x12\x14.proto.EventsRequest\x1a\x15.proto.EventsResponse\x12\x44\n\x0bInteraction\x12\x19.proto.InteractionRequest\x1a\x1a.proto.InteractionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hiperlink_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTSREQUEST._serialized_start=26
  _EVENTSREQUEST._serialized_end=66
  _EVENTSRESPONSE._serialized_start=68
  _EVENTSRESPONSE._serialized_end=99
  _INTERACTIONREQUEST._serialized_start=101
  _INTERACTIONREQUEST._serialized_end=164
  _INTERACTIONRESPONSE._serialized_start=166
  _INTERACTIONRESPONSE._serialized_end=202
  _PLUGIN._serialized_start=205
  _PLUGIN._serialized_end=624
# @@protoc_insertion_point(module_scope)
